apiVersion: v1
kind: Pod
metadata:
  name: ramya-fitnesstracker
  namespace: my-report

spec:
  containers:
    - name: ramya-fitnesstracker
      image: ramyar098/fitness-tracker
      ports:
        - containerPort: 3000